# Generated by Django 5.1.3 on 2024-12-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_tilt', models.DurationField()),
                ('right_tilt', models.DurationField()),
                ('lying_down_in_the_chair', models.DurationField()),
                ('bow', models.DurationField()),
                ('left_face', models.DurationField()),
                ('right_face', models.DurationField()),
                ('high_shoulder', models.DurationField()),
                ('low_shoulder', models.DurationField()),
                ('supporting_the_table', models.DurationField()),
                ('looking_up', models.DurationField()),
                ('normal', models.DurationField()),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'pose_records',
            },
        ),
    ]
