version: '2.29'

services:
  social:
    build: .
    restart: always

    volumes:
      - ./db:/home/server/db

    ports:
      - '8080:8080'
    command: [ "bash", "-c", "
      source ~/.bashrc
      && python manage.py makemigrations user updates
      && python manage.py migrate
      && gunicorn -w4 -b 0.0.0.0:8080 --log-level debug pose_remote.wsgi
      " ]

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - '80:8080'
    environment:
      SWAGGER_JSON: /spec/APIs.yaml
    volumes:
      - ./API-spec:/spec
