# Generated by Django 5.1.3 on 2024-12-05 02:41

from django.db import migrations, models

import updates.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('n_image', models.IntegerField(default=0)),
                ('image0', models.ImageField(null=True, upload_to=updates.models.post_image_path)),
                ('image1', models.ImageField(null=True, upload_to=updates.models.post_image_path)),
                ('image2', models.ImageField(null=True, upload_to=updates.models.post_image_path)),
                ('image3', models.ImageField(null=True, upload_to=updates.models.post_image_path)),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
